# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MeffDialog
                                 A QGIS plugin
 This plugin computes mesh effective size
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-05
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Mathieu Chailloux
        email                : mathieu@chailloux.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.core import QgsProcessingContext

from .shared import utils, progress, log
from .steps import params, landuse, fragm,  reporting
from . import tabs

class FragScapeModel:

    def __init__(self,context,feedback):
        self.context = None
        self.feedback = feedback
        utils.debug("feedback fs = " + str(feedback))
        self.paramsModel = params.ParamsModel(self)
        self.landuseModel = landuse.LanduseModel(self)
        self.fragmModel = fragm.FragmModel(self)
        self.reportingModel = reporting.ReportingModel(self)
        self.parser_name = "FragScapeModel"
        
    def checkWorkspaceInit(self):
        self.paramsModel.checkWorkspaceInit()
            
    # Returns relative path w.r.t. workspace directory.
    # File separator is set to common slash '/'.
    def normalizePath(self,path):
        return self.paramsModel.normalizePath(path)
            
    # Returns absolute path from normalized path (cf 'normalizePath' function)
    def getOrigPath(self,path):
        return self.paramsModel.getOrigPath(path)
    
    def mkOutputFile(self,name):
        return self.paramsModel.mkOutputFile(name)
        
    def runModel(self):
        utils.debug("feedback fs rm = " + str(self.feedback))
        self.landuseModel.applyItemsWithContext(self.context,self.feedback)
        self.fragmModel.applyItemsWithContext(self.context,self.feedback)
        self.reportingModel.runReportingWithContext(self.context,self.feedback)
        
    def toXML(self,indent=""):
        xmlStr = indent + "<" + self.parser_name + ">"
        new_indent = " "
        if self.paramsModel:
            xmlStr += "\n" + self.paramsModel.toXML(indent=new_indent)
        if self.landuseModel:
            xmlStr += "\n" + self.landuseModel.toXML(indent=new_indent)
        if self.fragmModel:
            xmlStr += "\n" + self.fragmModel.toXML(indent=new_indent)
        if self.reportingModel:
            xmlStr += "\n" + self.reportingModel.toXML(indent=new_indent)
        xmlStr += "\n" + indent + "</" + self.parser_name + ">"
        return xmlStr
        
    def fromXMLRoot(self,root):
        for child in root:
            utils.debug("tag = " + str(child.tag))
            if child.tag == self.paramsModel.parser_name:
                self.paramsModel.fromXMLRoot(child)
                self.paramsModel.layoutChanged.emit()
            elif child.tag == self.landuseModel.parser_name:
                self.landuseModel.fromXMLRoot(child)
                self.landuseModel.layoutChanged.emit()
            elif child.tag == self.fragmModel.parser_name:
                self.fragmModel.fromXMLRoot(child)
                self.fragmModel.layoutChanged.emit()
            elif child.tag == self.reportingModel.parser_name:
                self.reportingModel.fromXMLRoot(child)
                self.reportingModel.layoutChanged.emit()
        
        
class FragScapeConnector:

    def __init__(self,dlg):
        global progressFeedback
        self.dlg = dlg
        # Log connector must be instantiated first
        self.logConnector = log.LogConnector(self.dlg)
        self.logConnector.initGui()
        # Context and feedback initializations
        self.feedback =  progress.ProgressFeedback(self.dlg)
        progress.progressFeedback = self.feedback
        utils.debug("progressFeedback = " + str(progress.progressFeedback))
        self.context = QgsProcessingContext()
        self.context.setFeedback(progress.progressFeedback)
        # Model initialization
        self.fsModel = FragScapeModel(self.context,progress.progressFeedback)
        self.paramsConnector = params.ParamsConnector(self.dlg,self.fsModel.paramsModel)
        self.landuseConnector = landuse.LanduseConnector(self.dlg,self.fsModel.landuseModel)
        self.fragmConnector = fragm.FragmConnector(self.dlg,self.fsModel.fragmModel,self)
        self.reportingConnector = reporting.ReportingConnector(self.dlg,self.fsModel.reportingModel)
        self.tabConnector = tabs.TabConnector(self.dlg)
        self.connectors = [ self.logConnector,
                            self.paramsConnector,
                            self.landuseConnector,
                            self.fragmConnector,
                            self.reportingConnector,
                            self.feedback,
                            self.tabConnector]
        self.recomputeParsers()
        
        
    # Recompute self.parsers in case they have been reloaded
    def recomputeParsers(self):
        self.parsers = [self.paramsConnector,
                        self.landuseConnector,
                        self.fragmConnector.model,
                        self.reportingConnector]
    